// @ts-nocheck
import { AuditLog } from '../audit/AuditLog';

export interface IoTestCaseEvidence {
    caseId: string;
    input: string;
    expected: string;
    actual: string;
    passed: boolean;
    timedOut: boolean;
}

export interface HttpStep {
    method: string;
    url: string;
    status: number;
    requestBody?: any;
    responseBody?: any;
}

export interface CodeSnippetEvidence {
    codeSnippet: string;
    filePath?: string;
    startLine?: number;
    endLine?: number;
    explanation?: string;
}

export interface RuleEvidence {
    snippets?: CodeSnippetEvidence[];
    // Legacy single snippet for backward compatibility
    codeSnippet?: string;
    filePath?: string;
    startLine?: number;
    endLine?: number;
    httpSteps?: HttpStep[];
    screenshotBase64?: string;
    explanation?: string;
    ioTestCases?: IoTestCaseEvidence[];
    hybridBreakdown?: {
        codePct: number;
        probePct?: number;
        visionPct?: number;
        textPct?: number;
    };
    extractedImages?: { label: string; contentType: string; base64: string }[];
    studentText?: string;
}

export interface ScoredRule {
    ruleId: string;
    title: string;
    description?: string;
    weight: number;
    earnedScore: number;
    passed: boolean;
    evidenceIds: string[];
    evidence?: RuleEvidence;
    details?: string;
}

export interface AiFeedback {
    category: string;
    comments: string;
}

/**
 * The final, reproducible output generated by the RubricEvaluator.
 */
export interface AssessmentReport {
    submissionId: string;
    assignmentId: string;
    studentId: string;

    // Score Breakdown
    totalScore: number;
    maxPossibleScore: number;
    isPass: boolean;

    passedRules: ScoredRule[];
    failedRules: ScoredRule[];

    // Review and Feedback
    manualReviewNotes?: string[];
    aiFeedback?: AiFeedback[];
    overallFeedback?: string;
    error?: string;

    // Traceability
    auditMetadata: {
        evaluatorVersion: string;
        timestamp: string;
        auditLogIds: string[];
    };
}

